### ISSUE TITLE
Lage test for at eit begrep blir serialisert korrekt til skos-ap-no

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/concept-catalogue#101]
Vi må sikre at eit begrep på vår interne modell blir korrekt serialisert til skos-ap-no. Derfor må vi lage ein test som avdekker avvik.

Må teste følgande scenario:
* lage nytt begrep via BegreperApiImplK.kt,
* oppdatere status på begrepet til publisert,
* teste at begrepet blir blir korrekt serialisert fra HarvestEndpoint.kt

**Comment by sindresandvik2** [comment]
Forbedret SONAR stat!
38 nye tester kjører fint!
