### ISSUE TITLE
Heile modellen blir skrive til log for kvar høsting

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/concept-catalogue#111]
I HarvestEndpoint.kt skrives modellen som høstes til log. Sjekk linje 42. Dette gjer at loggen blir oversvømt og det er ikkje mogleg å skru dette av.

Enten må vi fjerne println, eller eventuelt erstatte med logger.trace(...) type statement.

**Comment by markkopaas** [comment]
bruk logger. da får vi severity filtrering. Vi allerede har logback json konfigurasjon på plass her. vi må bruke json logging i alle tjenestene.

**Comment by stigbd** [comment]
Enig. Men i dette tilfellet er det uavklart om det trengs logging i det heile teke. Eg stemmer for å fjerne.
