### ISSUE TITLE
Optional filter "status" ikke implementert på GET /begreper

### ISSUE THREAD

**Issue by markkopaas** [Informasjonsforvaltning/concept-catalogue#120]
minst vi kan kaste error "Not Implemented" hvis noen bruker det

**Comment by stigbd** [comment]
Bra. Enig. Vi bør gi 501 not implemented dersom konsument bruker query-parameter status.

**Comment by shenluna** [comment]
Testet OK
Eksempel fra staging
![image](https://user-images.githubusercontent.com/73637969/122178243-b30f5c80-ce86-11eb-8068-dedd3cfe6e45.png)
