### ISSUE TITLE
Kontrakttest for concept-catalogue

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/concept-catalogue#141]
Ta utgangspunkt i
a-frontend-service
a-backend-service

og verifiser at de ulike tjenestene har en specc fil.
Deretter skal vi skrive kontrakttester/featuretester for den enkelte tjenesten.

Implementere kontrakttest/featurestest for tjenesten:
concept-catalougue

**Comment by NilsOveTen** [comment]
Løses av https://github.com/Informasjonsforvaltning/concept-catalog/issues/3
