### ISSUE TITLE
Søk etter begrep i Se også feiler med server_error 500

### ISSUE THREAD

**Issue by joachim-me** [Informasjonsforvaltning/concept-catalogue#144]
DEMO-miljøet: Begrepskatalog (registrering): Søk etter begrep i Se også feiler med server_error 500

![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/22339de5-8c41-4f21-87df-e1b12f273e1a)

NB! Dette gjelder for datasettregistrering- når bruker skal knytte på begreper også.

**Comment by lillelars** [comment]
Fungerer nå som det skal. Lukker derfor denne.
