### ISSUE TITLE
API-registreringsløsning: Mange tomme oppføringer i API-katalogen som kan slettes

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/concept-catalogue#148]
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/705e52e4-dae7-43b1-9bbc-beed91690a19)

**Comment by valosnah** [comment]
API-beskrivelser slettet

**Comment by lillelars** [comment]
tom testdata er nå slettet.
