### ISSUE TITLE
Sørge for at concept-harvester høster skos-ap-no til portal

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/concept-catalogue#93]
NB! Start med en vurdering av denne oppgaven, så snakker du med en venn :) (Stig)

**Comment by stigbd** [comment]
Denne er litt uklar. FDK-concept-harvester (som er i eit anna repo) høster i dag skos-ap-no i concept-catalogue (dette repoet). Kva for mangel er det dette issuet adresserer?
