### ISSUE TITLE
BrukerId mangler i endringslogelement

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/concept-catalogue#99]
Ref følgende kommentar i BegreperAipImplK.kt:
```
endringslogelement.apply {
            endringstidspunkt = OffsetDateTime.now()
            brukerId = "todo" //TODO: When auth is ready read username from auth context
        }
```
Siden auth er klar, bør vi få på plass denne.

**Comment by stigbd** [comment]
Dette er ei backend-sak, for security-context får backend frå Spring. Men det er sjølvsagt ei forutsetning at brukerId blir sendt over frå front-end.

**Comment by oyvindis** [comment]
@stigbd da mener du vel at 'brukerId' sendes som en del av token? Så må 'brukerId' ikke tillates å bli patched direkte i 'endringslogelement' fra frontend.

Token sendes allerede så her skal det ikke være noe mer på frontend.

**Comment by sindresandvik2** [comment]
Retestet OK i UT1, men brukerID vises som f.nr.  Burde vært Brukernavn!
